In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("data/Para_juntar/Grande Base.csv",sep=',',encoding='latin1')

In [3]:
df.head()

,CD_PROGRAMA_IES,AN_BASE,CD_AREA_AVALIACAO,CONCEITO_PROGRAMA,IB_Total_docentes,IB_Mulheres,IB_Homens,IB_Brasileiros,IB_Estrangeiros,IB_QTDE_Regime_Parcial,...,CD_CONCEITO_PROGRAMA,Unnamed: 0,NM_MODALIDADE_PROGRAMA,UF_Qtd_Proj,UF_Pesquisas,UF_Outros projetos,UF_Qtd_Financiamentos,BOLSA,OUTRO AUXÃLIO FINANCEIRO,SEM AUXÃLIO
0,12001015018P0,2013,45,3,32,18,14,30,2,1,...,3,0,ACADÃMICO,9,8,1,19,13,5,1
1,12001015018P0,2013,45,3,32,18,14,30,2,1,...,3,75,ACADÃMICO,9,8,1,19,13,5,1
2,12001015018P0,2013,45,3,32,18,14,30,2,1,...,3,155,ACADÃMICO,9,8,1,19,13,5,1
3,12001015018P0,2013,45,3,32,18,14,30,2,1,...,3,0,ACADÃMICO,9,8,1,19,13,5,1
4,12001015018P0,2013,45,3,32,18,14,30,2,1,...,3,75,ACADÃMICO,9,8,1,19,13,5,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16800 entries, 0 to 16799
Data columns (total 61 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   CD_PROGRAMA_IES              16800 non-null  object
 1   AN_BASE                      16800 non-null  int64
 2   CD_AREA_AVALIACAO            16800 non-null  int64
 3   CONCEITO_PROGRAMA            16800 non-null  int64
 4   IB_Total_docentes            16800 non-null  int64
 5   IB_Mulheres                  16800 non-null  int64
 6   IB_Homens                    16800 non-null  int64
 7   IB_Brasileiros               16800 non-null  int64
 8   IB_Estrangeiros              16800 non-null  int64
 9   IB_QTDE_Regime_Parcial       16800 non-null  int64
 10  IB_QTDE_Regime_Integral      16800 non-null  int64
 11  IB_QTDE_Regime_Exclusivo     16800 non-null  int64
 12  IB_QTDE_Prof_Doutor          16800 non-null  int64
 13  IB_QTDE_Prof_NaoDoutor       16800 non-null  int64
 14  IB_QTDE_titulados_Brasil     16800 non-null  int64
 15  IB_QTDE_titulados_Exterior   16800 non-null  int64
 16  IB_Profs_Colaboradores       16800 non-null  int64
 17  IB_Profs_ServidoresPublicos  16800 non-null  int64
 18  IB_Profs_VinculoCLT          16800 non-null  int64
 19  IB_Profs_Aposentados         16800 non-null  int64
 20  IB_Profs_BolsaDeFixacao      16800 non-null  int64
 21  IB_Total_cursos              16800 non-null  int64
 22  MEDIA_CONCEITO_CURSO         16800 non-null  float64
 23  ID_SUBTIPO_PRODUCAO          16800 non-null  float64
 24  NM_SUBTIPO_PRODUCAO          16800 non-null  object
 25  IN_TRABALHO_MESMA_AREA       16800 non-null  float64
 26  NR_PAGINAS                   16136 non-null  float64
 27  GUS_Lingua_estrangeira       16800 non-null  int64
 28  GUS_Quantidade_Trabalhos     16800 non-null  int64
 29  GUS_Do_Homens                16800 non-null  int64
 30  GUS_Do_Mulheres              16800 non-null  int64
 31  GUS_Do_Brasileiros           16800 non-null  int64
 32  GUS_Do_Estrangeiros          16800 non-null  int64
 33  GUS_Quantidade_Docentes      16800 non-null  int64
 34  AN_NASCIMENTO_DOCENTE        16800 non-null  float64
 35  SG_ENTIDADE_ENSINO           16800 non-null  object
 36  GUS_Dis_Homens               16800 non-null  int64
 37  GUS_Dis_Mulheres             16800 non-null  int64
 38  GUS_Dis_Brasileiros          16800 non-null  int64
 39  GUS_Dis_Estrangeiros         16800 non-null  int64
 40  GUS_diferenca_idade          16800 non-null  float64
 41  GUS_razao_aluno_prof         16800 non-null  float64
 42  GUS_Quantidade_Discentes     16800 non-null  int64
 43  GUS_Dis_Prop_Homens          16800 non-null  float64
 44  GUS_Dis_Aluno_Tempo          16800 non-null  float64
 45  QT_MES_TITULACAO             16800 non-null  float64
 46  GUS_pag_por_aluno            16136 non-null  float64
 47  CS_STATUS_JURIDICO           16800 non-null  object
 48  AN_NASCIMENTO_DISCENTE       16800 non-null  float64
 49  NM_REGIAO                    16800 non-null  object
 50  SG_UF_PROGRAMA               16800 non-null  object
 51  CD_CONCEITO_PROGRAMA         16800 non-null  int64
 52  Unnamed: 0                   16800 non-null  int64
 53  NM_MODALIDADE_PROGRAMA       16800 non-null  object
 54  UF_Qtd_Proj                  16800 non-null  int64
 55  UF_Pesquisas                 16800 non-null  int64
 56  UF_Outros projetos           16800 non-null  int64
 57  UF_Qtd_Financiamentos        16800 non-null  int64
 58  BOLSA                        16800 non-null  int64
 59  OUTRO AUXÃLIO FINANCEIRO    16800 non-null  int64
 60  SEM AUXÃLIO                 16800 non-null  int64
dtypes: float64(12), int64(42), object(7)
memory usage: 7.8+ MB